services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
volumes:
  odoo-web-data:
  odoo-db-data:
